package main.br.usp.esi.enums;

public enum HorarioType {
	SEGUNDA_UM, SEGUNDA_DOIS, SEGUNDA_TRES, SEGUNDA_QUATRO, SEGUNDA_CINCO, SEGUNDA_SEIS,
	TERCA_UM, TERCA_DOIS, TERCA_TRES, TERCA_QUATRO, TERCA_CINCO, TERCA_SEIS,
	QUARTA_UM, QUARTA_DOIS, QUARTA_TRES, QUARTA_QUATRO, QUARTA_CINCO, QUARTA_SEIS,
	QUINTA_UM, QUINTA_DOIS, QUINTA_TRES, QUINTA_QUATRO, QUINTA_CINCO, QUINTA_SEIS,
	SEXTA_UM, SEXTA_DOIS, SEXTA_TRES, SEXTA_QUATRO, SEXTA_CINCO, SEXTA_SEIS,
	SABADO_UM, SABADO_DOIS, SABADO_TRES, SABADO_QUATRO, SABADO_CINCO, SABADO_SEIS
}
